---
language: python
services: docker

env:
  global:
    - ROLE_NAME: peering_manager
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu2004

install:
  - pip install ansible
  - pip install 'molecule[docker]' docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
