---
- name: ensure postgresql is ready
  service:
    name: postgresql
    state: started

- name: create postgresql database
  postgresql_db:
    name: "{{ peering_manager_database }}"
  become: true
  become_user: "{{ peering_manager_postgresql_user }}"

- name: create postgresql user
  postgresql_user:
    name: "{{ peering_manager_database_user }}"
    password: "{{ peering_manager_database_password }}"
    encrypted: true
    db: "{{ peering_manager_database }}"
    priv: ALL
  become: true
  become_user: "{{ peering_manager_postgresql_user }}"

- name: ensure redis is ready
  service:
    name: "{{ peering_manager_redis_service }}"
    state: started
