---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart peering-manager
  service:
    name: peering-manager
    state: restarted
  when: peering_manager_setup_systemd

- name: restart apache2
  service:
    name: "{{ peering_manager_apache2_service }}"
    state: restarted
  when: peering_manager_setup_web_frontend
