---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint -c molecule/default/yamllint.yml molecule/default/
platforms:
  - name: instance
    image: gmazoyer/ansible-docker-${MOLECULE_DISTRO:-debian10}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
